server:
  port: 9411
management:
  metrics:
    web:
      server:
        auto-time-requests: false #\u5173\u95ED\u81EA\u52A8\u68C0\u6D4B\u8BF7\u6C42
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lagou-springcloud?useUnicode=true&characterEncoding=utf8
    username: root
    password: shangyu
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      max-wait: 50000
zipkin:
  storage:
    type: mysql
