server:
  port: 9090
spring:
  application:
    name: lagou-cloud-stream-producer
  cloud:
    stream:
      binders:  #\u7ED1\u5B9Amq\u670D\u52A1\u4FE1\u606F\uFF08\u6B64\u5904\u6211\u4EEC\u662Fmq\uFF09
        lagouRabbitBinder:  #\u7ED9binder\u5B9A\u4E49\u7684\u540D\u79F0\uFF0C\u7528\u4E8E\u540E\u9762\u7684\u5173\u8054
          type: rabbit  #mq\u7C7B\u578B\uFF0C\u5982\u679C\u662Fkafka\u7684\u8BDD\uFF0C\u6B64\u5904\u914D\u7F6Ekafka
          environment: #mq\u73AF\u5883\u914D\u7F6E\uFF08\u7528\u6237\u540D\uFF0C\u5BC6\u7801\uFF09
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: #\u5173\u8054\u6574\u5408\u901A\u9053\u548Cbinder\u5BF9\u8C61
        output:  #output\u662F\u6211\u4EEC\u5B9A\u4E49\u7684\u901A\u9053\u540D\u79F0\uFF0C\u6B64\u5904\u4E0D\u80FD\u4E71\u6539
          destination: lagouExchange  #\u8981\u4F7F\u7528\u7684exchange\u540D\u79F0\uFF08\u6D88\u606F\u961F\u5217\u4E3B\u9898\u540D\u79F0\uFF09
          content-type: text/plain  #\u6D88\u606F\u7C7B\u578B\u8BBE\u7F6E
          binder: lagouRabbitBinder #\u5173\u8054mq\u670D\u52A1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    prefer-ip-address: true
